spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    # database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    open-in-view: true
    # show-sql: true
    # spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
